language: php
sudo: false
php:
  - 7.1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_script:
  - composer install

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_script:
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml
